trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - environment_setup/arm-templates/*
pr:
  branches:
    include:
    - develop
  paths:
    include:
    - environment_setup/arm-templates/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: MLOps-Library


steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: ''
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RESOURCE_GROUP_NAME)'
    location: $(LOCATION)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/environment_setup/arm-templates/cloud-environment.json'
    overrideParameters: '-baseName $(BASE_NAME) -location $(LOCATION)'
    deploymentMode: 'Incremental'
  displayName: 'Deploy services resources to Azure'
